### ISSUE TITLE
Webhooks has problem

### ISSUE THREAD

**Issue by danny50610** [HackerSir/IECSPT#3]
Please see detail in settings / Webhooks / Responses.
Need someone help me.

English~~

**Comment by jyhsu2000** [comment]
Folder `.git` must be belong to the account of apache ( such as `www-data`)
Maybe someone has used git commands and made ownership of the folder changed automatically.
Make sure that everything in project folder belong to apache's account, or be able to change by apache.

Hint: use `chown` command to reset ownership after using git command on server everytime.

**Comment by vongola12324** [comment]
I will add 's' mark to .git if you need.
The owner and group is www-data and staff, everyone is already in staff, but www-data.
